INSERT INTO movies (title, release_year, genre, poster_url, synopsis, duration_min, director) VALUES
('The Shawshank Redemption', 1994, 'Drama', 'https://picsum.photos/seed/movie1/300/450', 'A banker sentenced to life in prison forms a lasting friendship and holds on to hope.', 142, 'Frank Darabont'),
('The Godfather', 1972, 'Crime', 'https://picsum.photos/seed/movie2/300/450', 'The aging head of a crime family transfers control of his empire to his reluctant son.', 175, 'Francis Ford Coppola'),
('The Dark Knight', 2008, 'Action', 'https://picsum.photos/seed/movie3/300/450', 'Batman faces the Joker, a criminal mastermind determined to plunge Gotham into chaos.', 152, 'Christopher Nolan'),
('Pulp Fiction', 1994, 'Crime', 'https://picsum.photos/seed/movie4/300/450', 'Interwoven stories follow criminals and other figures through the Los Angeles underworld.', 154, 'Quentin Tarantino'),
('Forrest Gump', 1994, 'Drama', 'https://picsum.photos/seed/movie5/300/450', 'A kindhearted Alabama man witnesses decades of American history while pursuing his childhood love.', 142, 'Robert Zemeckis'),
('Inception', 2010, 'Sci-Fi', 'https://picsum.photos/seed/movie6/300/450', 'A skilled thief who enters dreams is offered a chance to erase his past by planting an idea.', 148, 'Christopher Nolan'),
('The Matrix', 1999, 'Sci-Fi', 'https://picsum.photos/seed/movie7/300/450', 'A hacker discovers that his world is a simulation and joins a rebellion against its machines.', 136, 'Lana Wachowski, Lilly Wachowski'),
('Parasite', 2019, 'Thriller', 'https://picsum.photos/seed/movie8/300/450', 'A struggling family gradually enters the lives of a wealthy household with unexpected consequences.', 132, 'Bong Joon Ho'),
('Spirited Away', 2001, 'Animation', 'https://picsum.photos/seed/movie9/300/450', 'A young girl enters a spirit world and must save her parents after they are transformed.', 125, 'Hayao Miyazaki'),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Fantasy', 'https://picsum.photos/seed/movie10/300/450', 'A hobbit begins a perilous journey to destroy a powerful ring before evil can reclaim it.', 178, 'Peter Jackson'),
('Interstellar', 2014, 'Sci-Fi', 'https://picsum.photos/seed/movie11/300/450', 'Explorers travel through a wormhole in search of a new home for humanity.', 169, 'Christopher Nolan'),
('City of God', 2002, 'Crime', 'https://picsum.photos/seed/movie12/300/450', 'Two boys take different paths while organized crime grows in a Rio de Janeiro neighborhood.', 130, 'Fernando Meirelles, Katia Lund'),
('The Silence of the Lambs', 1991, 'Thriller', 'https://picsum.photos/seed/movie13/300/450', 'An FBI trainee seeks an imprisoned psychiatrist''s help to catch a serial killer.', 118, 'Jonathan Demme'),
('Saving Private Ryan', 1998, 'War', 'https://picsum.photos/seed/movie14/300/450', 'A wartime squad crosses occupied France to bring a paratrooper home after D-Day.', 169, 'Steven Spielberg'),
('The Green Mile', 1999, 'Drama', 'https://picsum.photos/seed/movie15/300/450', 'A prison guard witnesses extraordinary events involving a gentle death-row inmate.', 189, 'Frank Darabont'),
('Whiplash', 2014, 'Drama', 'https://picsum.photos/seed/movie16/300/450', 'An ambitious jazz drummer is pushed to his limits by a ruthless instructor.', 106, 'Damien Chazelle'),
('Gladiator', 2000, 'Action', 'https://picsum.photos/seed/movie17/300/450', 'A betrayed Roman general becomes a gladiator and seeks justice against a corrupt emperor.', 155, 'Ridley Scott'),
('The Lion King', 1994, 'Animation', 'https://picsum.photos/seed/movie18/300/450', 'A young lion prince must reclaim his kingdom after the death of his father.', 88, 'Roger Allers, Rob Minkoff'),
('Back to the Future', 1985, 'Sci-Fi', 'https://picsum.photos/seed/movie19/300/450', 'A teenager travels to the 1950s and must ensure that his parents fall in love.', 116, 'Robert Zemeckis'),
('Alien', 1979, 'Horror', 'https://picsum.photos/seed/movie20/300/450', 'The crew of a commercial spacecraft encounters a lethal extraterrestrial organism.', 117, 'Ridley Scott'),
('The Pianist', 2002, 'Biography', 'https://picsum.photos/seed/movie21/300/450', 'A Polish Jewish musician struggles to survive the destruction of Warsaw during World War II.', 150, 'Roman Polanski'),
('The Departed', 2006, 'Crime', 'https://picsum.photos/seed/movie22/300/450', 'An undercover officer and a police informant race to uncover each other in Boston.', 151, 'Martin Scorsese'),
('The Prestige', 2006, 'Mystery', 'https://picsum.photos/seed/movie23/300/450', 'Two rival magicians pursue a dangerous obsession with creating the ultimate illusion.', 130, 'Christopher Nolan'),
('Coco', 2017, 'Animation', 'https://picsum.photos/seed/movie24/300/450', 'A young musician enters the Land of the Dead to discover his family''s history.', 105, 'Lee Unkrich'),
('Mad Max: Fury Road', 2015, 'Action', 'https://picsum.photos/seed/movie25/300/450', 'A drifter and a rebel warrior flee a tyrant across a post-apocalyptic wasteland.', 120, 'George Miller'),
('The Grand Budapest Hotel', 2014, 'Comedy', 'https://picsum.photos/seed/movie26/300/450', 'A devoted concierge and his lobby-boy protege become involved in a disputed inheritance.', 99, 'Wes Anderson'),
('Pan''s Labyrinth', 2006, 'Fantasy', 'https://picsum.photos/seed/movie27/300/450', 'A girl in postwar Spain discovers a mysterious labyrinth and a demanding mythical quest.', 118, 'Guillermo del Toro'),
('Get Out', 2017, 'Horror', 'https://picsum.photos/seed/movie28/300/450', 'A young man uncovers disturbing secrets while visiting his girlfriend''s family.', 104, 'Jordan Peele'),
('La La Land', 2016, 'Musical', 'https://picsum.photos/seed/movie29/300/450', 'An aspiring actress and a jazz pianist pursue their dreams and fall in love in Los Angeles.', 128, 'Damien Chazelle'),
('The Social Network', 2010, 'Biography', 'https://picsum.photos/seed/movie30/300/450', 'The creation of a social network leads to rapid success and bitter legal disputes.', 120, 'David Fincher');

INSERT INTO reviews (movie_id, author, rating, comment, created_at) VALUES
(1, 'Marina', 10, 'A moving story about patience, friendship, and hope.', '2026-07-02T14:20:00Z'),
(1, 'Rafael', 9, 'Powerful performances and an unforgettable ending.', '2026-07-18T09:15:00Z'),
(3, 'Lucas', 10, 'A tense superhero film with a remarkable villain.', '2026-07-20T19:30:00Z'),
(4, 'Camila', 8, 'Sharp dialogue and a structure that rewards attention.', '2026-06-11T22:10:00Z'),
(6, 'Bruno', 9, 'Ambitious, inventive, and visually impressive.', '2026-07-21T13:45:00Z'),
(6, 'Aline', 8, 'Complex but rewarding on a second viewing.', '2026-05-09T16:00:00Z'),
(7, 'Diego', 9, 'Its ideas and action still feel influential.', '2026-04-17T20:05:00Z'),
(8, 'Sofia', 10, 'Darkly funny, suspenseful, and brilliantly staged.', '2026-07-12T18:25:00Z'),
(9, 'Renata', 9, 'Beautiful animation and a wonderfully imaginative world.', '2026-03-28T11:40:00Z'),
(10, 'Pedro', 9, 'An epic beginning with a rich sense of adventure.', '2026-06-30T21:00:00Z'),
(11, 'Joana', 8, 'Emotional science fiction on an enormous scale.', '2026-07-08T15:35:00Z'),
(16, 'Mateus', 9, 'Intense editing and extraordinary musical performances.', '2026-07-19T23:10:00Z'),
(20, 'Beatriz', 9, 'Patient suspense followed by unforgettable horror.', '2026-02-14T10:50:00Z'),
(24, 'Gabriel', 8, 'A warm story about memory, music, and family.', '2026-06-22T17:20:00Z'),
(28, 'Larissa', 9, 'Clever social satire wrapped in an effective thriller.', '2026-07-16T12:30:00Z');

INSERT INTO favorites (movie_id) VALUES (3), (6), (9);
